apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  namespace: external-systems
  description: Workspace
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
  