apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  namespace: platformspec
  description: Developer Workspace
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
  