---
apiVersion: sdk.platformspec.io/v1alpha1
kind: PortalActionResource
metadata:
  name: backstage-create-namespace
  namespace: platformspec
spec:
  actionName: create-namespace
  description: Creates a new namespace
  labelSelector: category=portal,engine=kubernetes,action=create-namespace
  portalRef:
    apiVersion: core.platformspec.io/v1alpha1
    kind: Portal
    name: backstage
    namespace: platformspec
  config:
    name: ${{values.argo_project}}
    description: ${{values.name}}
    namespace: ${{values.namespace}}
    region: ${{values.region}}
    customer: ${{values.customer}}

